### ISSUE TITLE
Support updating note text without touching resources

### ISSUE THREAD

**Issue by hyouuu** [evernote/evernote-cloud-sdk-ios#106]
It looks like currently we can only upload an ENNote to replace another ENNoteRef entirely. However, if we only want to change the text, doing so would be very inefficient - i.e. all the images and other resources needed to be uploaded again without any change, and it will hit the 60MB threshold for free users very quickly.

Can we add an interface or param to indicate only text change? Thanks!

**Comment by everic** [comment]
Are you talking about using this API?

https://github.com/evernote/evernote-cloud-sdk-ios/blob/master/evernote-sdk-ios/ENSDK/ENSession.h#L333-L348

Have you verified that this API will cause the quota to be recalculated for the whole note including the resources? Thanks.

**Comment by hyouuu** [comment]
Yes that's the one I'm referring to. No I haven't verified - got some stuff to do before getting into the ENSDK, but even if the quota is not affected, it'd be still very wasteful considering how frequently the text can change

**Comment by everic** [comment]
Hello @hyouuu 
Thank you for bring up this question and concern

To wrap this up, this issue is not valid. If you update a note with existing resources, we won't be recalculating the quota for the resources that you have uploaded. The reason is, when you update a note, even when the resource you attached to it does not have a reference guid to the original uploaded resource, our service is calculating the MD5 hash of the binary data as the reference of the resource. Since the binary date is the same, we won't be recalculating the quota as a new upload.

To verify, I created this branch https://github.com/evernote/evernote-cloud-sdk-ios/tree/bug-106. You can check this out and use these two functions in the sample app to verify.
<img width="487" alt="screen_shot_2015-09-01_at_5_19_36_pm" src="https://cloud.githubusercontent.com/assets/7154385/9620316/bad44562-50cd-11e5-855e-5839a51da7b3.png">

I'm logging the quota use from the service after each time we upload and update the note. So each update with the PDF attached as a resource is only taking 21 bytes of quota, so you don't have to worry about this. :-)

**Comment by hyouuu** [comment]
Awesome to hear - thanks for digging in and the elaboration everic :+1:

**Comment by hyouuu** [comment]
It would be great if we add this tip into the method comment :)

**Comment by everic** [comment]
Yeah, added via https://github.com/evernote/evernote-cloud-sdk-ios/commit/5a5ca419e03403bc429b4b3ddd81fd522e665818

Thank you for bring this up @hyouuu
