### ISSUE TITLE
Unable to import the framework into swift project

### ISSUE THREAD

**Issue by VinayakKkini** [evernote/evernote-cloud-sdk-ios#135]
I have added the following line in my  project bridging header
# import <evernote_cloud_sdk_ios/ENSDK.h>

I get the following error: "could not build module "evernote_cloud_sdk_ios".  Also find the find build errors attached. I am using latest version of the SDK.

![screen shot 2016-08-19 at 11 14 42 am](https://cloud.githubusercontent.com/assets/14877931/17800191/98b8bbce-65fe-11e6-8c09-7c893e051dde.png)

**Comment by VinayakKkini** [comment]
Here is a sample project with which issue can be reproducible. https://drive.google.com/open?id=0B-zyqu5AigiRejVWMHRSU2pxZmM

**Comment by D-32** [comment]
I'm aware this isn't an ideal solution, but I got the SDK to work by including the files directly instead of using cocoapods.
Just copy all the files from the SDK into your project and add `#import "ENSDK.h"` to your bridging header file.
Also you have to add "libxml2" & "MobileCoreServices" to your `Link Binary With Libraries` section of your Build Phases.
After these steps I was able to use the Evernote SDK in a swift 3 project.

**Comment by D-32** [comment]
Also had to add `"$(SDKROOT)/usr/include/libxml2"` to "Header Search Paths" inside the Build Settings.

**Comment by VinayakKkini** [comment]
Hey @D-32 

We were able run the app without any issues. Thanks for the help.
Do have any plans to update the SDK to work with cocoapods?

**Comment by D-32** [comment]
I hope to look into it in January. Not promising anything here though :)

**Comment by imougy** [comment]
@VinayakKkini cocoapods working now.
