### ISSUE TITLE
ENSessionUploadPolicyReplace creates note when it should not

### ISSUE THREAD

**Issue by demosten** [evernote/evernote-cloud-sdk-ios#56]
Setup:
* Create a note in Business notebook
* Store ENNote and ENNoteRef to it
* Move the note to some of your personal notebooks (Using Evernote for Mac)
* Execite this code with your stored ENNote and ENNoteRef:
```Objective-C
[[ENSession sharedSession] uploadNote:note policy:ENSessionUploadPolicyReplace toNotebook:nil orReplaceNote:noteRef progress:nil completion:^(ENNoteRef *newNoteRef, NSError *error) {
	// ...
}];
```
* Now you have your note created back in you Business notebook. ENSessionUploadPolicyReplace should generate error instead of creating it I believe
* If you try the other way around (have your note to personal notebook and move it to business) an error is generated

**Comment by everic** [comment]
Hi @demosten 

Unfortunately this is expected based on our current Evernote Business logic

When you move a note from a business notebook to your personal notebook, technically, we created a note with the same content on your personal shard, and we marked the original business note as 'inactive' on the service, as only business admins are able to expunge business notes. And when you execute the uploadNote with replace policy, we tell the service to update the note with this guid to have a new note content, so our service is bring back the 'inactive/deleted' business note back to life. So that appear to users that we created a new note, but actually we never technically deleted the business note in the first place.

Since this is how our business logic works, not going to fix.

**Comment by demosten** [comment]
Hello @everic ,

I it might look fine from EN internal logic perspective, but we are talking API here. If the note is "deleted" regardless of whether it is really deleted or flagged internally a developer would expect API with ENSessionUploadPolicyReplace flag to throw an error if the note "does not exist" from user's perspective.

**Comment by everic** [comment]
Hi @demosten 
What would you expect when you are replacing a note in the trash? Do you want an error to be thrown? If in this case, then clients will not be able to restore a note in the trash.

**Comment by demosten** [comment]
Hello @everic

If the user "moves" it, does it still go to trash? In that case it can be replaced there but it should not go out of the trash probably? In any case my "replace" should not make something that is not there reappear. That's what "ENSessionUploadPolicyReplaceOrCreate" flag is for.

**Comment by everic** [comment]
Only when a user moves a note in business notebook to his personal one, the original note actually goes to trash while a copy of the note is created on his personal account. The reason is because we don't want Business Notes can be easily deleted.

https://github.com/evernote/evernote-cloud-sdk-ios/commit/29a3d18cf5ec64e7c74c64f4f8a0a2c35feb32d5 Should fix this. Now the replace policy does not update the note's active property, so trash notes remain in trash.
