### ISSUE TITLE
How can I create new notebook with SDK 2.0?

### ISSUE THREAD

**Issue by donobono** [evernote/evernote-cloud-sdk-ios#71]
Hello.. 
Today, I found your SDK has been updated totally. So I'm converting my sources with new SDK.
I think your SDK has been better and simpler.
But I cannot find how to create new notebook, I used createNotebook method in old SDK.
There is no way in your sample source(it is too simple) too.

Can you plz let me know how to do?

One more..
I'd like to make photo note like this form..

Text
Photo
Text
...

Photo
Text

I tried to upload new note with ENNote, I could add multiple photos, but only one text was able. 
I wonder which way is simplest..

Thank you..
Best regards..

**Comment by everic** [comment]
Should be fixed by https://github.com/evernote/evernote-cloud-sdk-ios/commit/93e658b987b1a2444c39b42cafed59e5394de2a5 and https://github.com/evernote/evernote-cloud-sdk-ios/commit/49374f29aa3f141d3305533340b713e0af868d4d

hello
@donobono 

I just updated the SDK sample app with functionalities to create notebooks and upload customized note like you mentioned. Thank you.

**Comment by donobono** [comment]
Hello
@everic 

I found from new sample.. Thank you so much.. :)
