### ISSUE TITLE
Can not authenticate via Evernote App for China service account

### ISSUE THREAD

**Issue by an0** [evernote/evernote-cloud-sdk-ios#74]
Frequently got this error:
Sign in Evernote failed: Error Domain=ENErrorDomain Code=11 "未能完成操作。（“ENErrorDomain”错误 11。）"

More specifically, after calling `-authenticateWithViewController:preferRegistration:completion:`, these happens in order:
1. A web view is presented.
2. Evernote app is launched.
3. Do nothing for 10 seconds.
4. My app's `-application:openURL:sourceApplication:annotation:` is called with url en-xxx://incorrectProfile/Evernote-China and my app comes to foreground.
5. Evernote app comes to foreground.
6. completion block is called with `authenticateError` above.
7. Evernote app present the authentication page.
8. I tap authenticate button.
9. `-application:openURL:sourceApplication:annotation:` is called again and my app comes to foreground. I can verify by reading the url that authentication succeeds. But it doesn't matter because completion block has already been called with error in step 6 and won't be called again for authentication success. So the whole authentication process failed.

It is a very critical issue for all Chinese users.

**Comment by everic** [comment]
Hello @an0 
Glad to see you here as I'm a user of 墨客

Recently we pushed out a new version of Evernote 7.6.4 which fixed a couple of authentication issue. While I'm investigating here with our team, can you check if this problem still happens with 7.6.4?

Thank you.

**Comment by an0** [comment]
@everic I'm glad to know that you use Moke:)

Unfortunately, this issue remains in the latest version of Evernote app. And because of #79 I can not test with the latest SDK.

**Comment by an0** [comment]
I tried the latest SDK. This issue remains. Now I have to set `self.authenticator.useWebAuthenticationOnly = YES` in `-authenticateWithViewController:preferRegistration:completion:` to avoid using Evernote app.

**Comment by everic** [comment]
Hi @an0 
https://github.com/evernote/evernote-cloud-sdk-ios/commit/869b21ed32c4a0b3afc00473cb6cf3f8fae7bad6 should fix the issue that we called the failed completion handler prematurely

The reason we're having two authentications is because as you're in US, our bootstrap server thinks you're authenticating to Evernote International the first time, and got a mismatch with the user logged in(印象笔记用户), so Evernote tells the 3rd party app to try again with 印象笔记. Second time the 3rd party app is authenticating to 印象笔记, and it should work and return you a success completion block.

Our client is anticipating the client to get the correct service to authenticate and then approve, for security reasons. We might change that in the future, but it currently works this way in our app. The only affected users (will see two auth flows) are users whose physical IP addresses are not in China but they have logged in a 印象笔记 account on their phones. All other cases should work without any issue.

Thank you.
