### ISSUE TITLE
Other resources type in ENMLUtility:convertENMLtoHTML 

### ISSUE THREAD

**Issue by ilia510** [evernote/evernote-cloud-sdk-ios#84]
Hello, @everic,

We have a ENMLUtility converter from ENML to HTML. However, for any other resource type except an image, the converter just removes <en-media> tags - it is here:

function (line 162):
- (void) writeResource:(EDAMResource*)resource
        withAttributes:(NSDictionary *)attributes

and condition:
 if ([mime hasPrefix:@"image/"] == YES) {
        [self writeImageTagForResource:resource
                        withAttributes:scrubbedAttributes];
    }
    else {
        // Ignoring all other resource types
    }

Could please change it to write  a href="http://example.com/"RESOURCE_HASH"."RESOURCE_TYPE"? 

I think it is pretty obvious, that any other resource type should have "a" tag.

I am using this function to transform ENML to HTML, and now I have to do many "voodoo" stuff to capture en-media that is not an image.

**Comment by everic** [comment]
Hi @ilia510 

I'm not sure what's your use case here, but I think if you're trying to find en-media, you should parse the original ENML content of a note instead of parsing the transformed HTML. The HTML transforming is subject to change and it's only acting as a preview tool for a note. Our note editors on various platforms are very complicated and they may render note in platform specific styles and formats, so relying on parsing the transformed HTML is not safe and not recommended IMHO.

But if you think the method is the only way to go then feel free to fork the SDK, but I don't think this change is necessary in the official Evernote Cloud SDK for iOS.
